spring:
  application:
    name: api-integration
server: 8099
api:
  base-url: ${API_BASE_URL:http://localhost:8081}
  key: ${API_KEY:secret-key}
  max-rps: ${API_MAX_RPS:10}
logging:
  level:
    edu.mikita.apiintegration: DEBUG
