spring:
  application:
    name: apiintegration
server:
  port: 8099
stock:
  api:
    base-url: ${API_BASE_URL:http://localhost:8081}
    key: ${API_KEY:demo-secret-key}
    max-rps: ${API_MAX_RPS:10}
logging:
  level:
    edu.mikita.apiintegration: DEBUG
