openapi: 3.0.1
info:
  title: Fake Stock API
  version: '1.0'
servers:
  - url: http://localhost:8081
paths:
  /stocks:
    get:
      tags:
        - Stock
      summary: Get list of stocks
      operationId: getStocks
      security:
        - ApiKeyAuth: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stock'
  /stocks/{id}:
    get:
      tags:
        - Stock
      summary: Get stock by ID
      operationId: getStockById
      security:
        - ApiKeyAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: Stock ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Stock found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'
        '404':
          description: Stock not found
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    Stock:
      type: object
      properties:
        id:
          type: integer
          format: int64
        symbol:
          type: string
        name:
          type: string
        price:
          type: number
          format: float
